namespace MarkOut;

/// <summary>
/// Contains metadata and serialization logic for a specific type.
/// Generated by the source generator for each [MarkOutSerializable] type.
/// </summary>
/// <typeparam name="T">The type this info represents.</typeparam>
public abstract class MarkOutTypeInfo<T>
{
    /// <summary>
    /// Gets the type this info represents.
    /// </summary>
    public Type Type => typeof(T);

    /// <summary>
    /// Serializes a value to the given MarkOutWriter.
    /// </summary>
    /// <param name="writer">The writer to serialize to.</param>
    /// <param name="value">The value to serialize.</param>
    public abstract void Serialize(MarkOutWriter writer, T value);
}
