namespace Markout;

/// <summary>
/// Non-generic interface for runtime enumeration of registered types.
/// </summary>
public interface IMarkoutTypeInfo
{
    /// <summary>
    /// Gets the type this info represents.
    /// </summary>
    Type Type { get; }

    /// <summary>
    /// Gets the template binding name for this type (snake_case).
    /// Used by <see cref="Templates.MarkoutTemplate.BindContext"/> for automatic registration.
    /// </summary>
    string BindingName { get; }

    /// <summary>
    /// Serializes a value to the given MarkoutWriter.
    /// </summary>
    /// <param name="writer">The writer to serialize to.</param>
    /// <param name="value">The value to serialize (must be of the correct type).</param>
    void Serialize(MarkoutWriter writer, object value);
}

/// <summary>
/// Contains metadata and serialization logic for a specific type.
/// Generated by the source generator for each [MarkoutSerializable] type.
/// </summary>
/// <typeparam name="T">The type this info represents.</typeparam>
public abstract class MarkoutTypeInfo<T> : IMarkoutTypeInfo
{
    /// <summary>
    /// Gets the type this info represents.
    /// </summary>
    public Type Type => typeof(T);

    /// <summary>
    /// Gets the template binding name for this type (snake_case).
    /// Generated from the type name: CveReport → cve_report.
    /// </summary>
    public abstract string BindingName { get; }

    /// <summary>
    /// Serializes a value to the given MarkoutWriter.
    /// </summary>
    /// <param name="writer">The writer to serialize to.</param>
    /// <param name="value">The value to serialize.</param>
    public abstract void Serialize(MarkoutWriter writer, T value);

    /// <summary>
    /// Serializes a value to the given MarkoutWriter (non-generic implementation).
    /// </summary>
    void IMarkoutTypeInfo.Serialize(MarkoutWriter writer, object value)
    {
        Serialize(writer, (T)value);
    }
}
