namespace Markout;

/// <summary>
/// Contains metadata and serialization logic for a specific type.
/// Generated by the source generator for each [MarkoutSerializable] type.
/// </summary>
/// <typeparam name="T">The type this info represents.</typeparam>
public abstract class MarkoutTypeInfo<T>
{
    /// <summary>
    /// Gets the type this info represents.
    /// </summary>
    public Type Type => typeof(T);

    /// <summary>
    /// Serializes a value to the given MarkoutWriter.
    /// </summary>
    /// <param name="writer">The writer to serialize to.</param>
    /// <param name="value">The value to serialize.</param>
    public abstract void Serialize(MarkoutWriter writer, T value);
}
