<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Markout.Ansi.Spectre</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Description>Spectre.Console renderer for Markout</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Markout\Markout.csproj" />
    <PackageReference Include="Spectre.Console" Version="0.54.0" />
  </ItemGroup>

</Project>
