using System.IO;
using System.Linq;
using Markout;
using Xunit;

namespace Markout.Tests;

/// <summary>
/// Tests that verify the structure and correctness of generated source code.
/// These "golden" tests catch regressions in the source generator's emission.
/// </summary>
public class GeneratedCodeTests
{
    private static readonly string GeneratedDir = Path.GetFullPath(Path.Combine(
        AppContext.BaseDirectory, "..", "..", "..", "..",
        "artifacts", "obj", "Markout.Tests", "debug", "generated",
        "Markout.SourceGeneration",
        "Markout.SourceGeneration.MarkoutSourceGenerator"));

    private static string ReadGenerated(string fileName)
    {
        var path = Path.Combine(GeneratedDir, fileName);
        Assert.True(File.Exists(path), $"Generated file not found: {path}");
        return File.ReadAllText(path);
    }

    [Fact]
    public void Generated_SimpleRecord_HasAutoGeneratedHeader()
    {
        var code = ReadGenerated("Markout.Tests.SimpleRecordMarkoutTypeInfo.g.cs");
        Assert.StartsWith("// <auto-generated/>", code);
    }

    [Fact]
    public void Generated_SimpleRecord_HasNullableEnable()
    {
        var code = ReadGenerated("Markout.Tests.SimpleRecordMarkoutTypeInfo.g.cs");
        Assert.Contains("#nullable enable", code);
    }

    [Fact]
    public void Generated_SimpleRecord_InheritsMarkoutTypeInfo()
    {
        var code = ReadGenerated("Markout.Tests.SimpleRecordMarkoutTypeInfo.g.cs");
        Assert.Contains(": global::Markout.MarkoutTypeInfo<Markout.Tests.SimpleRecord>", code);
    }

    [Fact]
    public void Generated_SimpleRecord_HasStaticInstance()
    {
        var code = ReadGenerated("Markout.Tests.SimpleRecordMarkoutTypeInfo.g.cs");
        Assert.Contains("public static SimpleRecordMarkoutTypeInfo Instance { get; } = new();", code);
    }

    [Fact]
    public void Generated_SimpleRecord_HasNullCheck()
    {
        var code = ReadGenerated("Markout.Tests.SimpleRecordMarkoutTypeInfo.g.cs");
        Assert.Contains("if (value == null) return;", code);
    }

    [Fact]
    public void Generated_SimpleRecord_SkipsIgnoredProperty()
    {
        var code = ReadGenerated("Markout.Tests.SimpleRecordMarkoutTypeInfo.g.cs");
        // SimpleRecord has [MarkoutIgnore] on Secret
        Assert.DoesNotContain("Secret", code);
    }

    [Fact]
    public void Generated_SimpleRecord_UsesCustomDisplayName()
    {
        var code = ReadGenerated("Markout.Tests.SimpleRecordMarkoutTypeInfo.g.cs");
        // SimpleRecord has [MarkoutPropertyName("Display Name")] on Name
        Assert.Contains("\"Display Name\"", code);
    }

    [Fact]
    public void Generated_Context_HasDefaultProperty()
    {
        var code = ReadGenerated("Markout.Tests.TestMarkoutContext.g.cs");
        Assert.Contains("public static TestMarkoutContext Default { get; } = new();", code);
    }

    [Fact]
    public void Generated_Context_HasGetTypeInfoMethod()
    {
        var code = ReadGenerated("Markout.Tests.TestMarkoutContext.g.cs");
        Assert.Contains("public override global::Markout.MarkoutTypeInfo<T>? GetTypeInfo<T>()", code);
    }

    [Fact]
    public void Generated_Context_HasGetSchemaInfoMethod()
    {
        var code = ReadGenerated("Markout.Tests.TestMarkoutContext.g.cs");
        Assert.Contains("public override global::Markout.MarkoutSchemaInfo? GetSchemaInfo<T>()", code);
    }

    [Fact]
    public void Generated_BoldContext_HasOptionsConstructor()
    {
        var code = ReadGenerated("Markout.Tests.BoldContext.g.cs");
        Assert.Contains("BoldFieldNames = true", code);
        Assert.Contains("base(new global::Markout.MarkoutWriterOptions", code);
    }

    [Fact]
    public void Generated_Package_HasTableEmission()
    {
        var code = ReadGenerated("Markout.Tests.PackageMarkoutTypeInfo.g.cs");
        Assert.Contains("writer.WriteTableStart(", code);
        Assert.Contains("writer.WriteTableRow(", code);
        Assert.Contains("writer.WriteTableEnd()", code);
    }

    [Fact]
    public void Generated_Enum_UsesToString()
    {
        var code = ReadGenerated("Markout.Tests.TaskItemMarkoutTypeInfo.g.cs");
        Assert.Contains(".ToString()", code);
    }

    [Fact]
    public void Generated_Formattable_UsesWriteTo()
    {
        var code = ReadGenerated("Markout.Tests.PersonWithAddressMarkoutTypeInfo.g.cs");
        Assert.Contains("IMarkoutFormattable", code);
        Assert.Contains(".WriteTo(writer)", code);
    }
}
