<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <ItemGroup>
    <ProjectReference Include="$(MSBuildThisFileDirectory)..\src\Markout\Markout.csproj" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)..\src\Markout.SourceGeneration\Markout.SourceGeneration.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="true" />
  </ItemGroup>
</Project>
