using System.Collections.Generic;
using System.Linq;
using System.Text;
using Markout.SourceGeneration.Parser;

namespace Markout.SourceGeneration.Emitter;

/// <summary>
/// Emits source code for Markout serialization.
/// </summary>
internal static class SerializerEmitter
{
    public static string EmitTypeInfo(TypeMetadata type)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(type.Namespace))
        {
            sb.AppendLine($"namespace {type.Namespace};");
            sb.AppendLine();
        }

        var className = $"{type.TypeName}MarkoutTypeInfo";

        sb.AppendLine($"public sealed class {className} : global::Markout.MarkoutTypeInfo<{type.FullTypeName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public static {className} Instance {{ get; }} = new();");
        sb.AppendLine();
        sb.AppendLine($"    public override void Serialize(global::Markout.MarkoutWriter writer, {type.FullTypeName} value)");
        sb.AppendLine("    {");
        if (!type.IsValueType)
        {
            sb.AppendLine("        if (value == null) return;");
            sb.AppendLine();
        }

        // Emit title (H1) if TitleProperty is set
        if (!string.IsNullOrEmpty(type.TitleProperty))
        {
            var titleProp = type.Properties.FirstOrDefault(p => p.Name == type.TitleProperty);
            var contextProp = !string.IsNullOrEmpty(type.TitleContextProperty)
                ? type.Properties.FirstOrDefault(p => p.Name == type.TitleContextProperty)
                : null;

            if (titleProp != null)
            {
                if (contextProp != null)
                {
                    // Title with context: WriteHeading(1, title, context)
                    sb.AppendLine($"        if (value.{titleProp.Name} != null)");
                    sb.AppendLine($"            writer.WriteHeading(1, value.{titleProp.Name}, value.{contextProp.Name});");
                }
                else
                {
                    // Title only
                    sb.AppendLine($"        if (value.{titleProp.Name} != null)");
                    sb.AppendLine($"            writer.WriteHeading(1, value.{titleProp.Name});");
                }
                sb.AppendLine();
            }
        }

        // Emit description paragraph if DescriptionProperty is set
        if (!string.IsNullOrEmpty(type.DescriptionProperty))
        {
            var descProp = type.Properties.FirstOrDefault(p => p.Name == type.DescriptionProperty);
            if (descProp != null)
            {
                sb.AppendLine($"        if (writer.IncludeDescription && value.{descProp.Name} != null)");
                sb.AppendLine($"            writer.WriteParagraph(value.{descProp.Name});");
                sb.AppendLine();
            }
        }

        var propsToRender = type.Properties;
        if (type.TitleProperty != null || type.TitleContextProperty != null || type.DescriptionProperty != null)
        {
            var skip = new HashSet<string>();
            if (type.TitleProperty != null) skip.Add(type.TitleProperty);
            if (type.TitleContextProperty != null) skip.Add(type.TitleContextProperty);
            if (type.DescriptionProperty != null) skip.Add(type.DescriptionProperty);
            propsToRender = type.Properties.Where(p => !skip.Contains(p.Name)).ToList();
        }

        EmitPropertySerializations(sb, propsToRender, "value", 2, 2, 0, type.RenderScalars, type.FieldLayout);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitContext(ContextMetadata context)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(context.Namespace))
        {
            sb.AppendLine($"namespace {context.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {context.ClassName}");
        sb.AppendLine("{");

        // Constructor accepting options
        sb.AppendLine($"    public {context.ClassName}() {{ }}");
        sb.AppendLine($"    public {context.ClassName}(global::Markout.MarkoutWriterOptions options) : base(options) {{ }}");
        sb.AppendLine();

        // Static Default property
        sb.AppendLine($"    public static {context.ClassName} Default {{ get; }} = new();");
        sb.AppendLine();

        // Type info properties for each type
        foreach (var type in context.Types)
        {
            var typeInfoClass = GetTypeInfoClassName(type);
            sb.AppendLine($"    public {typeInfoClass} {type.TypeName} {{ get; }} = {typeInfoClass}.Instance;");
        }

        sb.AppendLine();

        // GetTypeInfo<T> implementation
        sb.AppendLine("    public override global::Markout.MarkoutTypeInfo<T>? GetTypeInfo<T>()");
        sb.AppendLine("    {");

        foreach (var type in context.Types)
        {
            var typeInfoClass = GetTypeInfoClassName(type);
            sb.AppendLine($"        if (typeof(T) == typeof({type.FullTypeName}))");
            sb.AppendLine($"            return (global::Markout.MarkoutTypeInfo<T>)(object){typeInfoClass}.Instance;");
        }

        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GetSchemaInfo<T> implementation
        sb.AppendLine("    public override global::Markout.MarkoutSchemaInfo? GetSchemaInfo<T>()");
        sb.AppendLine("    {");

        foreach (var type in context.Types)
        {
            sb.AppendLine($"        if (typeof(T) == typeof({type.FullTypeName}))");
            sb.AppendLine($"            return {type.TypeName}Schema;");
        }

        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Schema properties for each type
        foreach (var type in context.Types)
        {
            EmitSchemaProperty(sb, type);
        }

        // Section name constants for each type that has sections
        foreach (var type in context.Types)
        {
            EmitSectionConstants(sb, type);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitSchemaProperty(StringBuilder sb, TypeMetadata type)
    {
        sb.AppendLine($"    private static global::Markout.MarkoutSchemaInfo? _{type.TypeName}Schema;");
        sb.AppendLine($"    public static global::Markout.MarkoutSchemaInfo {type.TypeName}Schema => _{type.TypeName}Schema ??= new()");
        sb.AppendLine("    {");
        sb.AppendLine($"        TypeName = \"{type.TypeName}\",");
        sb.AppendLine($"        AsDocument = new global::Markout.MarkoutPropertySchema[]");
        sb.AppendLine("        {");
        EmitSchemaProperties(sb, type.Properties, false, 3);
        sb.AppendLine("        },");
        sb.AppendLine($"        AsTableItem = new global::Markout.MarkoutPropertySchema[]");
        sb.AppendLine("        {");
        EmitSchemaProperties(sb, type.Properties, true, 3);
        sb.AppendLine("        }");
        sb.AppendLine("    };");
        sb.AppendLine();
    }

    private static void EmitSchemaProperties(StringBuilder sb, IReadOnlyList<PropertyMetadata> properties, bool inTableContext, int indentLevel)
    {
        var indent = new string(' ', indentLevel * 4);

        foreach (var prop in properties)
        {
            var rendering = GetRenderingDescription(prop, inTableContext);
            
            sb.AppendLine($"{indent}new()");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    Name = \"{prop.Name}\",");
            sb.AppendLine($"{indent}    DisplayName = \"{EscapeString(prop.DisplayName)}\",");
            sb.AppendLine($"{indent}    TypeName = \"{EscapeString(GetSimpleTypeName(prop.TypeName))}\",");
            sb.AppendLine($"{indent}    Rendering = \"{EscapeString(rendering)}\",");
            
            // Only show children for non-ignored properties in document context
            if (prop.ElementProperties != null && prop.ElementProperties.Count > 0 && !inTableContext && !prop.IsIgnored)
            {
                sb.AppendLine($"{indent}    Children = new global::Markout.MarkoutPropertySchema[]");
                sb.AppendLine($"{indent}    {{");
                // For sections, show child properties as they would render
                var childInTable = prop.Kind == PropertyKind.ComplexArray && !prop.ElementHasNestedContent;
                EmitSchemaProperties(sb, prop.ElementProperties, childInTable, indentLevel + 2);
                sb.AppendLine($"{indent}    }}");
            }
            else
            {
                sb.AppendLine($"{indent}    Children = global::System.Array.Empty<global::Markout.MarkoutPropertySchema>()");
            }
            
            sb.AppendLine($"{indent}}},");
        }
    }

    private static void EmitSectionConstants(StringBuilder sb, TypeMetadata type)
    {
        var sectionProps = type.Properties
            .Where(p => p.IsSection && !p.IsIgnored)
            .ToList();

        if (sectionProps.Count == 0)
            return;

        sb.AppendLine($"    public static class {type.TypeName}Sections");
        sb.AppendLine("    {");

        var usedNames = new HashSet<string>();
        foreach (var prop in sectionProps)
        {
            var sectionName = prop.SectionName ?? prop.DisplayName;
            var constName = NormalizeSectionName(sectionName);

            // Ensure uniqueness by appending a suffix if needed
            var uniqueName = constName;
            var suffix = 2;
            while (!usedNames.Add(uniqueName))
            {
                uniqueName = constName + suffix;
                suffix++;
            }

            sb.AppendLine($"        public const string {uniqueName} = \"{EscapeString(sectionName)}\";");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string NormalizeSectionName(string name)
    {
        // Replace non-alphanumeric characters with spaces, then PascalCase join
        var cleaned = new StringBuilder(name.Length);
        foreach (var ch in name)
        {
            cleaned.Append(char.IsLetterOrDigit(ch) ? ch : ' ');
        }

        var parts = cleaned.ToString().Split(new[] { ' ' }, System.StringSplitOptions.RemoveEmptyEntries);
        var result = new StringBuilder();
        foreach (var part in parts)
        {
            result.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
                result.Append(part.Substring(1));
        }
        return result.ToString();
    }

    private static string GetRenderingDescription(PropertyMetadata prop, bool inTableContext)
    {
        if (inTableContext)
        {
            if (prop.IsIgnored)
                return "Ignored";
            
            if (prop.IsIgnoredInTable)
                return "Ignored";
            
            // In table context, only scalars work
            if (IsScalarKind(prop.Kind))
                return "Column" + (prop.Name != prop.DisplayName ? $" \"{prop.DisplayName}\"" : "");
            
            // Unsupported patterns are skipped
            if (prop.IsUnsupportedInTable)
                return "Skipped (unsupported)";
            
            return "Column";
        }

        if (prop.IsIgnored)
            return "Ignored";

        // Document context - [MarkoutIgnoreInTable] has no effect here
        if (prop.IsSection)
        {
            var sectionName = prop.SectionName ?? prop.DisplayName;
            if (prop.Kind == PropertyKind.FieldCollection)
                return $"H{prop.SectionLevel} Section \"{sectionName}\" (field table)";
            if (prop.Kind == PropertyKind.ComplexArray)
            {
                if (prop.ElementHasNestedContent)
                    return $"H{prop.SectionLevel} Section \"{sectionName}\" (subsections)";
                return $"H{prop.SectionLevel} Section \"{sectionName}\" (table)";
            }
            if (prop.Kind == PropertyKind.NestedObject)
                return $"H{prop.SectionLevel} Section \"{sectionName}\" (fields)";
            if (prop.Kind == PropertyKind.Tree)
                return $"H{prop.SectionLevel} Section \"{sectionName}\" (tree)";
            return $"H{prop.SectionLevel} Section \"{sectionName}\"";
        }

        return prop.Kind switch
        {
            PropertyKind.String => "Field",
            PropertyKind.Boolean => "Field (yes/no)",
            PropertyKind.Int32 or PropertyKind.Int64 => "Field",
            PropertyKind.Double or PropertyKind.Decimal => "Field",
            PropertyKind.DateTime or PropertyKind.DateTimeOffset => "Field (ISO 8601)",
            PropertyKind.StringArray => "Bullet list",
            PropertyKind.ComplexArray => prop.ElementHasNestedContent 
                ? "Subsections" 
                : "Table",
            PropertyKind.FieldCollection => "Compact fields",
            PropertyKind.NestedObject => "Fields",
            PropertyKind.Tree => "Tree",
            _ => "Field"
        };
    }

    private static string GetSimpleTypeName(string fullTypeName)
    {
        // Simplify common type names
        return fullTypeName
            .Replace("System.Collections.Generic.List<", "List<")
            .Replace("System.String", "string")
            .Replace("System.Int32", "int")
            .Replace("System.Int64", "long")
            .Replace("System.Boolean", "bool")
            .Replace("System.Decimal", "decimal")
            .Replace("System.Double", "double");
    }

    private static bool IsScalarKind(PropertyKind kind)
    {
        return kind is
            PropertyKind.String or
            PropertyKind.Boolean or
            PropertyKind.Int32 or
            PropertyKind.Int64 or
            PropertyKind.Double or
            PropertyKind.Decimal or
            PropertyKind.DateTime or
            PropertyKind.DateTimeOffset;
    }

    private static string GetTypeInfoClassName(TypeMetadata type)
    {
        if (string.IsNullOrEmpty(type.Namespace))
            return $"global::{type.TypeName}MarkoutTypeInfo";
        return $"global::{type.Namespace}.{type.TypeName}MarkoutTypeInfo";
    }

    private static void EmitPropertySerializations(
        StringBuilder sb,
        IReadOnlyList<PropertyMetadata> properties,
        string valueExpr,
        int indentLevel,
        int baseHeadingLevel = 2,
        int nestingDepth = 0,
        bool renderScalars = true,
        FieldLayoutKind fieldLayout = FieldLayoutKind.OneLine)
    {
        var indent = new string(' ', indentLevel * 4);

        // Separate scalars from non-scalars for field layout handling
        var scalarProps = new List<PropertyMetadata>();
        var nonScalarProps = new List<PropertyMetadata>();

        foreach (var prop in properties)
        {
            if (prop.IsIgnored)
                continue;

            // Skip non-section properties if RenderScalars is false
            if (!renderScalars && !prop.IsSection && prop.Kind != PropertyKind.FieldCollection)
                continue;

            if (IsScalarKind(prop.Kind) && !prop.IsSection)
                scalarProps.Add(prop);
            else
                nonScalarProps.Add(prop);
        }

        // Emit scalars based on layout
        if (renderScalars && scalarProps.Count > 0)
        {
            EmitScalarsWithLayout(sb, scalarProps, valueExpr, indentLevel, fieldLayout, nestingDepth);
        }

        // Emit non-scalar properties (sections, arrays, etc.)
        foreach (var prop in nonScalarProps)
        {
            var propAccess = $"{valueExpr}.{prop.Name}";
            var effectiveSectionLevel = prop.IsSection 
                ? System.Math.Max(prop.SectionLevel, baseHeadingLevel) 
                : baseHeadingLevel;

            if (prop.IsSection)
            {
                var sectionName = prop.SectionName ?? prop.DisplayName;

                if (prop.Kind == PropertyKind.FieldCollection)
                {
                    // List<MarkoutField> or IReadOnlyList<MarkoutField> with [MarkoutSection] renders as field table
                    sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.Count > 0)");
                    sb.AppendLine($"{indent}{{");
                    sb.AppendLine($"{indent}    writer.WriteHeading({effectiveSectionLevel}, \"{EscapeString(sectionName)}\");");
                    sb.AppendLine($"{indent}    writer.WriteFieldTable({propAccess});");
                    sb.AppendLine($"{indent}}}");
                }
                else if (prop.Kind == PropertyKind.ComplexArray && prop.ElementProperties != null)
                {
                    sb.AppendLine($"{indent}if ({GetCollectionCountCheck(prop, propAccess)})");
                    sb.AppendLine($"{indent}{{");
                    sb.AppendLine($"{indent}    writer.WriteHeading({effectiveSectionLevel}, \"{EscapeString(sectionName)}\");");
                    
                    if (prop.ElementHasNestedContent)
                    {
                        // Render as subsection-per-item
                        EmitSubsectionPerItemSerialization(sb, prop, propAccess, indentLevel + 1, effectiveSectionLevel, nestingDepth);
                    }
                    else
                    {
                        // Render as table
                        EmitTableSerialization(sb, prop, propAccess, indentLevel + 1, nestingDepth);
                    }
                    sb.AppendLine($"{indent}}}");
                }
                else if (prop.Kind == PropertyKind.StringArray)
                {
                    sb.AppendLine($"{indent}if ({GetCollectionCountCheck(prop, propAccess)})");
                    sb.AppendLine($"{indent}{{");
                    sb.AppendLine($"{indent}    writer.WriteHeading({effectiveSectionLevel}, \"{EscapeString(sectionName)}\");");
                    sb.AppendLine($"{indent}    writer.WriteArray({propAccess});");
                    sb.AppendLine($"{indent}}}");
                }
                else if (prop.Kind == PropertyKind.Tree)
                {
                    // List<TreeNode> with [MarkoutSection] renders as section with tree
                    sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.Count > 0)");
                    sb.AppendLine($"{indent}{{");
                    sb.AppendLine($"{indent}    writer.WriteHeading({effectiveSectionLevel}, \"{EscapeString(sectionName)}\");");
                    sb.AppendLine($"{indent}    writer.WriteTree({propAccess});");
                    sb.AppendLine($"{indent}}}");
                }
                else if (prop.Kind == PropertyKind.NestedObject && prop.ElementProperties != null)
                {
                    sb.AppendLine($"{indent}if ({propAccess} != null)");
                    sb.AppendLine($"{indent}{{");
                    sb.AppendLine($"{indent}    writer.WriteHeading({effectiveSectionLevel}, \"{EscapeString(sectionName)}\");");
                    EmitPropertySerializations(sb, prop.ElementProperties, propAccess, indentLevel + 1, effectiveSectionLevel + 1, nestingDepth + 1);
                    sb.AppendLine($"{indent}}}");
                }
                else
                {
                    // For other types, just write the heading unconditionally
                    sb.AppendLine($"{indent}writer.WriteHeading({effectiveSectionLevel}, \"{EscapeString(sectionName)}\");");
                }
                continue;
            }

            // Non-scalar property handling
            switch (prop.Kind)
            {
                case PropertyKind.StringArray:
                    sb.AppendLine($"{indent}if ({propAccess} != null)");
                    sb.AppendLine($"{indent}    writer.WriteArray(\"{EscapeString(prop.DisplayName)}\", {propAccess});");
                    break;

                case PropertyKind.FieldCollection:
                    // List<MarkoutField> or IReadOnlyList<MarkoutField> - renders as compact line
                    sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.Count > 0)");
                    sb.AppendLine($"{indent}    writer.WriteCompactFields({propAccess});");
                    break;

                case PropertyKind.Tree:
                    // List<TreeNode> - renders as tree structure
                    sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.Count > 0)");
                    sb.AppendLine($"{indent}    writer.WriteTree({propAccess});");
                    break;

                case PropertyKind.ComplexArray:
                    if (prop.ElementProperties != null && prop.ElementProperties.Count > 0)
                    {
                        sb.AppendLine($"{indent}if ({GetCollectionCountCheck(prop, propAccess)})");
                        sb.AppendLine($"{indent}{{");
                        sb.AppendLine($"{indent}    writer.WriteHeading({baseHeadingLevel}, \"{EscapeString(prop.DisplayName)}\");");
                        if (prop.ElementHasNestedContent)
                        {
                            EmitSubsectionPerItemSerialization(sb, prop, propAccess, indentLevel + 1, baseHeadingLevel, nestingDepth);
                        }
                        else
                        {
                            EmitTableSerialization(sb, prop, propAccess, indentLevel + 1, nestingDepth);
                        }
                        sb.AppendLine($"{indent}}}");
                    }
                    break;

                case PropertyKind.NestedObject:
                    if (prop.ElementProperties != null && prop.ElementProperties.Count > 0)
                    {
                        sb.AppendLine($"{indent}if ({propAccess} != null)");
                        sb.AppendLine($"{indent}{{");
                        sb.AppendLine($"{indent}    writer.WriteHeading({baseHeadingLevel}, \"{EscapeString(prop.DisplayName)}\");");
                        EmitPropertySerializations(sb, prop.ElementProperties, propAccess, indentLevel + 1, baseHeadingLevel + 1, nestingDepth + 1, true, fieldLayout);
                        sb.AppendLine($"{indent}}}");
                    }
                    break;
            }
        }
    }

    private static void EmitScalarsWithLayout(
        StringBuilder sb,
        List<PropertyMetadata> scalarProps,
        string valueExpr,
        int indentLevel,
        FieldLayoutKind fieldLayout,
        int nestingDepth = 0)
    {
        switch (fieldLayout)
        {
            case FieldLayoutKind.OneLine:
                EmitOneLineScalars(sb, scalarProps, valueExpr, indentLevel, nestingDepth);
                break;

            case FieldLayoutKind.LineBreaks:
                EmitLineBreaksScalars(sb, scalarProps, valueExpr, indentLevel, doubleSpace: false);
                break;

            case FieldLayoutKind.LineBreaksDoubleSpace:
                EmitLineBreaksScalars(sb, scalarProps, valueExpr, indentLevel, doubleSpace: true);
                break;

            case FieldLayoutKind.List:
                EmitListScalars(sb, scalarProps, valueExpr, indentLevel);
                break;

            default:
                EmitOneLineScalars(sb, scalarProps, valueExpr, indentLevel, nestingDepth);
                break;
        }
    }

    private static void EmitOneLineScalars(
        StringBuilder sb,
        List<PropertyMetadata> scalarProps,
        string valueExpr,
        int indentLevel,
        int nestingDepth = 0)
    {
        var indent = new string(' ', indentLevel * 4);
        bool useBuilder = scalarProps.Any(p => p.IsNullableValueType || p.Kind == PropertyKind.String);
        var fieldsVar = nestingDepth == 0 ? "__fields" : $"__fields{nestingDepth}";

        if (useBuilder)
        {
            // Use List<MarkoutField> builder pattern when any scalar is nullable or string (to skip nulls/empties)
            sb.AppendLine($"{indent}var {fieldsVar} = new global::System.Collections.Generic.List<global::Markout.MarkoutField>();");
            foreach (var prop in scalarProps)
            {
                var propAccess = $"{valueExpr}.{prop.Name}";
                if (prop.IsNullableValueType)
                {
                    var valueStr = GetScalarValueExpression(prop, propAccess, nullable: true);
                    sb.AppendLine($"{indent}if ({propAccess}.HasValue)");
                    sb.AppendLine($"{indent}    {fieldsVar}.Add(new global::Markout.MarkoutField(\"{EscapeString(prop.DisplayName)}\", {valueStr}));");
                }
                else if (prop.Kind == PropertyKind.String)
                {
                    sb.AppendLine($"{indent}if (!string.IsNullOrEmpty({propAccess}))");
                    sb.AppendLine($"{indent}    {fieldsVar}.Add(new global::Markout.MarkoutField(\"{EscapeString(prop.DisplayName)}\", {propAccess}));");
                }
                else
                {
                    var valueStr = GetScalarValueExpression(prop, propAccess);
                    sb.AppendLine($"{indent}{fieldsVar}.Add(new global::Markout.MarkoutField(\"{EscapeString(prop.DisplayName)}\", {valueStr}));");
                }
            }
            sb.AppendLine($"{indent}if ({fieldsVar}.Count > 0)");
            sb.AppendLine($"{indent}    writer.WriteCompactFields({fieldsVar});");
        }
        else
        {
            // Build inline MarkoutField array (no nullable/string scalars)
            var fields = new List<string>();
            foreach (var prop in scalarProps)
            {
                var propAccess = $"{valueExpr}.{prop.Name}";
                var valueStr = GetScalarValueExpression(prop, propAccess);
                fields.Add($"new global::Markout.MarkoutField(\"{EscapeString(prop.DisplayName)}\", {valueStr})");
            }

            sb.AppendLine($"{indent}writer.WriteCompactFields({string.Join(", ", fields)});");
        }
    }

    private static void EmitLineBreaksScalars(
        StringBuilder sb,
        List<PropertyMetadata> scalarProps,
        string valueExpr,
        int indentLevel,
        bool doubleSpace)
    {
        var indent = new string(' ', indentLevel * 4);
        var methodName = doubleSpace ? "WriteField" : "WriteFieldNoBreak";

        foreach (var prop in scalarProps)
        {
            var propAccess = $"{valueExpr}.{prop.Name}";

            if (prop.IsNullableValueType)
            {
                sb.AppendLine($"{indent}if ({propAccess}.HasValue)");
                if (prop.Kind == PropertyKind.Boolean)
                {
                    if (prop.BoolTrueValue != null && prop.BoolFalseValue != null)
                    {
                        sb.AppendLine($"{indent}    writer.{methodName}(\"{EscapeString(prop.DisplayName)}\", {propAccess}.Value ? \"{EscapeString(prop.BoolTrueValue)}\" : \"{EscapeString(prop.BoolFalseValue)}\");");
                    }
                    else
                    {
                        sb.AppendLine($"{indent}    writer.{methodName}(\"{EscapeString(prop.DisplayName)}\", {propAccess}.Value);");
                    }
                }
                else if (prop.CustomFormat != null)
                {
                    sb.AppendLine($"{indent}    writer.{methodName}(\"{EscapeString(prop.DisplayName)}\", {propAccess}.Value.ToString(\"{EscapeString(prop.CustomFormat)}\", System.Globalization.CultureInfo.InvariantCulture));");
                }
                else
                {
                    sb.AppendLine($"{indent}    writer.{methodName}(\"{EscapeString(prop.DisplayName)}\", {propAccess}.Value);");
                }
            }
            else if (prop.Kind == PropertyKind.String)
            {
                sb.AppendLine($"{indent}if ({propAccess} != null)");
                sb.AppendLine($"{indent}    writer.{methodName}(\"{EscapeString(prop.DisplayName)}\", {propAccess});");
            }
            else if (prop.Kind == PropertyKind.Boolean)
            {
                if (prop.BoolTrueValue != null && prop.BoolFalseValue != null)
                {
                    sb.AppendLine($"{indent}writer.{methodName}(\"{EscapeString(prop.DisplayName)}\", {propAccess} ? \"{EscapeString(prop.BoolTrueValue)}\" : \"{EscapeString(prop.BoolFalseValue)}\");");
                }
                else
                {
                    sb.AppendLine($"{indent}writer.{methodName}(\"{EscapeString(prop.DisplayName)}\", {propAccess});");
                }
            }
            else if (prop.CustomFormat != null)
            {
                sb.AppendLine($"{indent}writer.{methodName}(\"{EscapeString(prop.DisplayName)}\", {propAccess}.ToString(\"{EscapeString(prop.CustomFormat)}\", System.Globalization.CultureInfo.InvariantCulture));");
            }
            else
            {
                sb.AppendLine($"{indent}writer.{methodName}(\"{EscapeString(prop.DisplayName)}\", {propAccess});");
            }
        }
    }

    private static void EmitListScalars(
        StringBuilder sb,
        List<PropertyMetadata> scalarProps,
        string valueExpr,
        int indentLevel)
    {
        var indent = new string(' ', indentLevel * 4);

        foreach (var prop in scalarProps)
        {
            var propAccess = $"{valueExpr}.{prop.Name}";

            if (prop.IsNullableValueType)
            {
                var valueStr = GetScalarValueExpression(prop, propAccess, nullable: true);
                sb.AppendLine($"{indent}if ({propAccess}.HasValue)");
                sb.AppendLine($"{indent}    writer.WriteListItem($\"{EscapeString(prop.DisplayName)}: {{{valueStr}}}\");");
            }
            else if (prop.Kind == PropertyKind.String)
            {
                sb.AppendLine($"{indent}if ({propAccess} != null)");
                sb.AppendLine($"{indent}    writer.WriteListItem($\"{EscapeString(prop.DisplayName)}: {{{propAccess}}}\");");
            }
            else
            {
                var valueStr = GetScalarValueExpression(prop, propAccess);
                sb.AppendLine($"{indent}writer.WriteListItem($\"{EscapeString(prop.DisplayName)}: {{{valueStr}}}\");");
            }
        }
    }

    private static string GetScalarValueExpression(PropertyMetadata prop, string propAccess, bool nullable = false)
    {
        var access = nullable ? $"{propAccess}.Value" : propAccess;

        if (prop.Kind == PropertyKind.Boolean && prop.BoolTrueValue != null && prop.BoolFalseValue != null)
        {
            return $"({access} ? \"{EscapeString(prop.BoolTrueValue)}\" : \"{EscapeString(prop.BoolFalseValue)}\")";
        }

        // Custom format overrides default formatting for formattable types
        if (prop.CustomFormat != null)
        {
            if (prop.Kind is PropertyKind.Int32 or PropertyKind.Int64 or PropertyKind.Double or PropertyKind.Decimal
                or PropertyKind.DateTime or PropertyKind.DateTimeOffset)
            {
                return $"{access}.ToString(\"{EscapeString(prop.CustomFormat)}\", System.Globalization.CultureInfo.InvariantCulture)";
            }
        }

        return prop.Kind switch
        {
            PropertyKind.Boolean => $"({access} ? \"yes\" : \"no\")",
            PropertyKind.String => $"{propAccess} ?? \"\"",
            PropertyKind.Int32 or PropertyKind.Int64 or PropertyKind.Double or PropertyKind.Decimal
                => $"{access}.ToString(System.Globalization.CultureInfo.InvariantCulture)",
            PropertyKind.DateTime or PropertyKind.DateTimeOffset
                => $"{access}.ToString(\"O\", System.Globalization.CultureInfo.InvariantCulture)",
            _ => $"{propAccess}?.ToString() ?? \"\""
        };
    }

    private static void EmitTableSerialization(
        StringBuilder sb,
        PropertyMetadata prop,
        string propAccess,
        int indentLevel,
        int nestingDepth = 0)
    {
        if (prop.ElementProperties == null || prop.ElementProperties.Count == 0)
            return;

        var indent = new string(' ', indentLevel * 4);
        var visibleProps = prop.ElementProperties.Where(p => !p.IsIgnored).ToList();
        var itemVar = nestingDepth == 0 ? "item" : $"item{nestingDepth}";

        // Build header array
        var headers = string.Join(", ", visibleProps.Select(p => $"\"{EscapeString(p.DisplayName)}\""));
        sb.AppendLine($"{indent}writer.WriteTableStart({headers});");

        sb.AppendLine($"{indent}foreach (var {itemVar} in {propAccess})");
        sb.AppendLine($"{indent}{{");

        // Build row values
        var values = new List<string>();
        foreach (var elemProp in visibleProps)
        {
            var value = GetTableCellValue(elemProp, itemVar);
            values.Add(value);
        }

        sb.AppendLine($"{indent}    writer.WriteTableRow({string.Join(", ", values)});");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine($"{indent}writer.WriteTableEnd();");
    }

    private static void EmitSubsectionPerItemSerialization(
        StringBuilder sb,
        PropertyMetadata prop,
        string propAccess,
        int indentLevel,
        int parentSectionLevel = 2,
        int nestingDepth = 0)
    {
        if (prop.ElementProperties == null || prop.ElementProperties.Count == 0)
            return;

        var indent = new string(' ', indentLevel * 4);
        var subsectionLevel = parentSectionLevel + 1;
        var itemVar = nestingDepth == 0 ? "item" : $"item{nestingDepth}";

        sb.AppendLine($"{indent}foreach (var {itemVar} in {propAccess})");
        sb.AppendLine($"{indent}{{");

        // Write subsection heading using TitleProperty or first string property
        if (!string.IsNullOrEmpty(prop.ElementTitleProperty))
        {
            sb.AppendLine($"{indent}    if ({itemVar}.{prop.ElementTitleProperty} != null)");
            sb.AppendLine($"{indent}        writer.WriteHeading({subsectionLevel}, {itemVar}.{prop.ElementTitleProperty});");
        }
        else
        {
            // Try to find a suitable property for the heading
            var titleProp = prop.ElementProperties.FirstOrDefault(p => 
                !p.IsIgnored && p.Kind == PropertyKind.String && 
                (p.Name == "Name" || p.Name == "Title" || p.Name == "Id"));
            
            if (titleProp != null)
            {
                sb.AppendLine($"{indent}    if ({itemVar}.{titleProp.Name} != null)");
                sb.AppendLine($"{indent}        writer.WriteHeading({subsectionLevel}, {itemVar}.{titleProp.Name});");
            }
            else
            {
                // Fallback: use first string property
                var firstString = prop.ElementProperties.FirstOrDefault(p => !p.IsIgnored && p.Kind == PropertyKind.String);
                if (firstString != null)
                {
                    sb.AppendLine($"{indent}    if ({itemVar}.{firstString.Name} != null)");
                    sb.AppendLine($"{indent}        writer.WriteHeading({subsectionLevel}, {itemVar}.{firstString.Name});");
                }
            }
        }

        // Emit property serializations for each item, at a deeper level
        EmitPropertySerializations(sb, prop.ElementProperties, itemVar, indentLevel + 1, subsectionLevel + 1, nestingDepth + 1);

        sb.AppendLine($"{indent}}}");
    }

    private static string GetTableCellValue(PropertyMetadata prop, string itemExpr)
    {
        var propAccess = $"{itemExpr}.{prop.Name}";

        if (prop.IsNullableValueType)
        {
            var valueExpr = GetScalarValueExpression(prop, propAccess, nullable: true);
            return $"{propAccess}.HasValue ? {valueExpr} : \"\"";
        }

        if (prop.Kind == PropertyKind.Boolean && prop.BoolTrueValue != null && prop.BoolFalseValue != null)
        {
            return $"{propAccess} ? \"{EscapeString(prop.BoolTrueValue)}\" : \"{EscapeString(prop.BoolFalseValue)}\"";
        }

        // Custom format overrides default formatting for formattable types
        if (prop.CustomFormat != null)
        {
            if (prop.Kind is PropertyKind.Int32 or PropertyKind.Int64 or PropertyKind.Double or PropertyKind.Decimal
                or PropertyKind.DateTime or PropertyKind.DateTimeOffset)
            {
                return $"{propAccess}.ToString(\"{EscapeString(prop.CustomFormat)}\", System.Globalization.CultureInfo.InvariantCulture)";
            }
        }

        return prop.Kind switch
        {
            PropertyKind.Boolean => $"{propAccess} ? \"yes\" : \"no\"",
            PropertyKind.String => $"{propAccess} ?? \"\"",
            PropertyKind.Int32 or PropertyKind.Int64 or PropertyKind.Double or PropertyKind.Decimal
                => $"{propAccess}.ToString(System.Globalization.CultureInfo.InvariantCulture)",
            PropertyKind.DateTime or PropertyKind.DateTimeOffset
                => $"{propAccess}.ToString(\"O\", System.Globalization.CultureInfo.InvariantCulture)",
            _ => $"{propAccess}?.ToString() ?? \"\""
        };
    }

    private static string GetCollectionCountCheck(PropertyMetadata prop, string propAccess)
    {
        var countProp = prop.IsArray ? "Length" : "Count";
        return $"{propAccess} != null && {propAccess}.{countProp} > 0";
    }

    private static string EscapeString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
