using System.Collections.Generic;
using System.Linq;
using System.Text;
using Markout.SourceGeneration.Parser;

namespace Markout.SourceGeneration.Emitter;

/// <summary>
/// Coordinates source code emission for Markout serialization.
/// Delegates to <see cref="FieldEmitter"/> for scalar field layouts,
/// <see cref="CollectionEmitter"/> for tables and subsections,
/// and <see cref="EmitHelpers"/> for shared value expressions.
/// </summary>
internal static class SerializerEmitter
{
    public static string EmitTypeInfo(TypeMetadata type, bool isPublic = true)
    {
        var sb = new StringBuilder();
        var accessModifier = isPublic ? "public" : "internal";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8602 // Dereference of a possibly null reference.");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(type.Namespace))
        {
            sb.AppendLine($"namespace {type.Namespace};");
            sb.AppendLine();
        }

        var className = $"{type.TypeName}MarkoutTypeInfo";

        // Collect section properties for per-section hooks
        var sectionProps = type.Properties.Where(p => p.IsSection && !p.IsIgnored).ToList();

        var bindingName = EmitHelpers.ToSnakeCase(type.TypeName);

        sb.AppendLine($"{accessModifier} partial class {className} : global::Markout.MarkoutTypeInfo<{type.FullTypeName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public static {className} Instance {{ get; }} = new();");
        sb.AppendLine();
        sb.AppendLine($"    public override string BindingName => \"{bindingName}\";");
        sb.AppendLine();
        sb.AppendLine($"    public override void Serialize(global::Markout.MarkoutWriter writer, {type.FullTypeName} value)");
        sb.AppendLine("    {");
        if (!type.IsValueType)
        {
            sb.AppendLine("        if (value == null) return;");
            sb.AppendLine();
        }

        sb.AppendLine("        OnSerializing(writer, value);");

        // Tree layout: title as plain-text root node, then tree properties only
        if (type.Layout == DocumentLayoutKind.Tree)
        {
            if (!string.IsNullOrEmpty(type.TitleProperty))
            {
                var titleProp = type.Properties.FirstOrDefault(p => p.Name == type.TitleProperty);
                if (titleProp != null)
                {
                    sb.AppendLine($"        if (value.{titleProp.Name} != null)");
                    sb.AppendLine($"            writer.WriteTreeNode(value.{titleProp.Name});");
                    sb.AppendLine();
                }
            }

            // Emit only tree properties
            foreach (var prop in type.Properties)
            {
                if (prop.IsIgnored || prop.Kind != PropertyKind.Tree) continue;
                var propAccess = $"value.{prop.Name}";
                sb.AppendLine($"        if ({propAccess} != null && {propAccess}.Count > 0)");
                sb.AppendLine($"            writer.WriteTree(global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan({propAccess}));");
            }

            sb.AppendLine();
            sb.AppendLine("        OnSerialized(writer, value);");
            sb.AppendLine("    }");
        }
        else
        {

        // Emit title (H1) if TitleProperty is set — opens document section
        var hasTitle = false;
        if (!string.IsNullOrEmpty(type.TitleProperty))
        {
            var titleProp = type.Properties.FirstOrDefault(p => p.Name == type.TitleProperty);
            var contextProp = !string.IsNullOrEmpty(type.TitleContextProperty)
                ? type.Properties.FirstOrDefault(p => p.Name == type.TitleContextProperty)
                : null;

            if (titleProp != null)
            {
                hasTitle = true;
                if (contextProp != null)
                {
                    sb.AppendLine($"        if (value.{titleProp.Name} != null)");
                    sb.AppendLine($"            writer.WriteSectionStart(1, value.{titleProp.Name}, value.{contextProp.Name});");
                }
                else
                {
                    sb.AppendLine($"        if (value.{titleProp.Name} != null)");
                    sb.AppendLine($"            writer.WriteSectionStart(1, value.{titleProp.Name});");
                }
                sb.AppendLine();
            }
        }

        // Emit description paragraph if DescriptionProperty is set
        if (!string.IsNullOrEmpty(type.DescriptionProperty))
        {
            var descProp = type.Properties.FirstOrDefault(p => p.Name == type.DescriptionProperty);
            if (descProp != null)
            {
                sb.AppendLine($"        if (writer.IncludeDescription && value.{descProp.Name} != null)");
                sb.AppendLine($"            writer.WriteParagraph(value.{descProp.Name});");
                sb.AppendLine();
            }
        }

        var propsToRender = type.Properties;
        if (type.TitleProperty != null || type.TitleContextProperty != null || type.DescriptionProperty != null)
        {
            var skip = new HashSet<string>();
            if (type.TitleProperty != null) skip.Add(type.TitleProperty);
            if (type.TitleContextProperty != null) skip.Add(type.TitleContextProperty);
            if (type.DescriptionProperty != null) skip.Add(type.DescriptionProperty);
            propsToRender = type.Properties.Where(p => !skip.Contains(p.Name)).ToList();
        }

        EmitPropertySerializations(sb, propsToRender, "value", 2, 2, 0, type.AutoFields, type.AutoFieldsCount, type.FieldLayout, "value", type.FullTypeName);

        sb.AppendLine();
        sb.AppendLine("        OnSerialized(writer, value);");
        if (hasTitle)
            sb.AppendLine("        writer.WriteSectionEnd();");
        sb.AppendLine("    }");

        } // end else (Document layout)
        sb.AppendLine();
        // Emit partial method declarations for hooks
        sb.AppendLine($"    partial void OnSerializing(global::Markout.MarkoutWriter writer, {type.FullTypeName} value);");
        sb.AppendLine($"    partial void OnSerialized(global::Markout.MarkoutWriter writer, {type.FullTypeName} value);");

        // Emit per-section hooks (deduplicate by name for sections sharing the same heading)
        var emittedHooks = new HashSet<string>();
        foreach (var sectionProp in sectionProps)
        {
            var hookName = sectionProp.SectionName ?? sectionProp.DisplayName;
            var safeName = new string(hookName.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());
            if (emittedHooks.Add(safeName))
                sb.AppendLine($"    partial void OnBeforeSection{safeName}(global::Markout.MarkoutWriter writer, {type.FullTypeName} value, ref bool skip);");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitContext(ContextMetadata context)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(context.Namespace))
        {
            sb.AppendLine($"namespace {context.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {context.ClassName}");
        sb.AppendLine("{");

        // Constructor accepting options
        if (context.BoldFieldNames != null || context.IncludeBadges != null || context.IncludeDescription != null)
        {
            // Generate default constructor that applies compile-time options
            sb.AppendLine($"    public {context.ClassName}() : base(new global::Markout.MarkoutWriterOptions");
            sb.AppendLine("    {");
            if (context.BoldFieldNames != null)
                sb.AppendLine($"        BoldFieldNames = {(context.BoldFieldNames.Value ? "true" : "false")},");
            if (context.IncludeBadges != null)
                sb.AppendLine($"        IncludeBadges = {(context.IncludeBadges.Value ? "true" : "false")},");
            if (context.IncludeDescription != null)
                sb.AppendLine($"        IncludeDescription = {(context.IncludeDescription.Value ? "true" : "false")},");
            sb.AppendLine("    }) { }");
        }
        else
        {
            sb.AppendLine($"    public {context.ClassName}() {{ }}");
        }
        sb.AppendLine($"    public {context.ClassName}(global::Markout.MarkoutWriterOptions options) : base(options) {{ }}");
        sb.AppendLine();

        // Static Default property
        sb.AppendLine($"    public static {context.ClassName} Default {{ get; }} = new();");
        sb.AppendLine();

        // Type info properties for each type
        foreach (var type in context.Types)
        {
            var typeInfoClass = GetTypeInfoClassName(type);
            sb.AppendLine($"    public {typeInfoClass} {type.TypeName} {{ get; }} = {typeInfoClass}.Instance;");
        }

        sb.AppendLine();

        // GetTypeInfo<T> implementation
        sb.AppendLine("    public override global::Markout.MarkoutTypeInfo<T>? GetTypeInfo<T>()");
        sb.AppendLine("    {");

        foreach (var type in context.Types)
        {
            var typeInfoClass = GetTypeInfoClassName(type);
            sb.AppendLine($"        if (typeof(T) == typeof({type.FullTypeName}))");
            sb.AppendLine($"            return (global::Markout.MarkoutTypeInfo<T>)(object){typeInfoClass}.Instance;");
        }

        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GetSchemaInfo<T> implementation
        sb.AppendLine("    public override global::Markout.MarkoutSchemaInfo? GetSchemaInfo<T>()");
        sb.AppendLine("    {");

        foreach (var type in context.Types)
        {
            sb.AppendLine($"        if (typeof(T) == typeof({type.FullTypeName}))");
            sb.AppendLine($"            return {type.TypeName}Schema;");
        }

        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GetRegisteredTypes implementation
        sb.AppendLine("    public override global::System.Collections.Generic.IEnumerable<global::Markout.IMarkoutTypeInfo> GetRegisteredTypes()");
        sb.AppendLine("    {");
        foreach (var type in context.Types)
        {
            var typeInfoClass = GetTypeInfoClassName(type);
            sb.AppendLine($"        yield return {typeInfoClass}.Instance;");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // Schema properties for each type
        foreach (var type in context.Types)
        {
            EmitSchemaProperty(sb, type);
        }

        // Section name constants for each type that has sections
        foreach (var type in context.Types)
        {
            EmitSectionConstants(sb, type);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    // EmitPropertySerializations is internal so CollectionEmitter can call back into it
    // for recursive subsection rendering.
    internal static void EmitPropertySerializations(
        StringBuilder sb,
        IReadOnlyList<PropertyMetadata> properties,
        string valueExpr,
        int indentLevel,
        int baseHeadingLevel = 2,
        int nestingDepth = 0,
        bool autoFields = true,
        int autoFieldsCount = 0,
        FieldLayoutKind fieldLayout = FieldLayoutKind.Table,
        string? rootValueExpr = null,
        string? rootTypeName = null)
    {
        // Cap heading level at H6 (Markdown maximum)
        if (baseHeadingLevel > 6) baseHeadingLevel = 6;

        var indent = new string(' ', indentLevel * 4);

        // Separate into three groups:
        // 1. rootScalars — scalars without [MarkoutSection] (auto fields at document root)
        // 2. scalarSectionGroups — scalars WITH [MarkoutSection], grouped by SectionName
        // 3. compoundProps — collections, trees, nested objects (unchanged)
        var rootScalars = new List<PropertyMetadata>();
        var scalarSectionGroups = new List<(string SectionName, List<PropertyMetadata> Props, PropertyMetadata FirstProp)>();
        var scalarSectionLookup = new Dictionary<string, List<PropertyMetadata>>();
        var compoundProps = new List<PropertyMetadata>();

        // Track emit ordering by first-occurrence index across all compound property types
        // SectionName=null for non-section compound props (emitted inline in declaration order)
        var emitOrder = new List<(string? SectionName, bool IsScalar, PropertyMetadata? NonSectionProp)>();
        var seenSections = new HashSet<string>();

        foreach (var prop in properties)
        {
            if (prop.IsIgnored)
                continue;

            // Skip non-section properties if AutoFields is false
            if (!autoFields && !prop.IsSection && prop.Kind != PropertyKind.FieldCollection)
                continue;

            bool isScalarKind = EmitHelpers.IsScalarKind(prop.Kind) || EmitHelpers.IsJoinedArray(prop);

            if (isScalarKind && !prop.IsSection)
            {
                rootScalars.Add(prop);
            }
            else if (isScalarKind && prop.IsSection)
            {
                var sectionName = prop.SectionName ?? prop.DisplayName;
                if (!scalarSectionLookup.TryGetValue(sectionName, out var group))
                {
                    group = new List<PropertyMetadata>();
                    scalarSectionLookup[sectionName] = group;
                    scalarSectionGroups.Add((sectionName, group, prop));
                }
                group.Add(prop);

                if (seenSections.Add(sectionName))
                    emitOrder.Add((sectionName, true, null));
            }
            else
            {
                compoundProps.Add(prop);
                if (prop.IsSection)
                {
                    var sectionName = prop.SectionName ?? prop.DisplayName;
                    if (seenSections.Add(sectionName))
                        emitOrder.Add((sectionName, false, null));
                }
                else
                {
                    emitOrder.Add((null, false, prop));
                }
            }
        }

        // Emit root scalars
        if (autoFields && rootScalars.Count > 0)
        {
            var scalarsToEmit = autoFieldsCount > 0 ? rootScalars.Take(autoFieldsCount).ToList() : rootScalars;
            FieldEmitter.EmitScalarsWithLayout(sb, scalarsToEmit, valueExpr, indentLevel, fieldLayout, nestingDepth);
        }

        // Build lookup for compound section props by name for ordered emission
        var compoundSectionProps = new Dictionary<string, List<PropertyMetadata>>();
        foreach (var prop in compoundProps)
        {
            if (prop.IsSection)
            {
                var sectionName = prop.SectionName ?? prop.DisplayName;
                if (!compoundSectionProps.TryGetValue(sectionName, out var list))
                {
                    list = new List<PropertyMetadata>();
                    compoundSectionProps[sectionName] = list;
                }
                list.Add(prop);
            }
        }

        // Emit compound properties in declaration order (sections, scalar sections, and non-sections interleaved)
        foreach (var (sectionName, isScalar, nonSectionProp) in emitOrder)
        {
            if (nonSectionProp != null)
            {
                var propAccess = $"{valueExpr}.{nonSectionProp.Name}";
                EmitNonSectionProperty(sb, nonSectionProp, propAccess, indent, indentLevel, baseHeadingLevel, nestingDepth, fieldLayout);
            }
            else if (isScalar)
            {
                var group = scalarSectionGroups.First(g => g.SectionName == sectionName);
                EmitScalarSectionGroup(sb, group.Props, group.FirstProp, sectionName!, valueExpr, indent, indentLevel, baseHeadingLevel, nestingDepth, fieldLayout, rootValueExpr, rootTypeName);
            }
            else
            {
                if (compoundSectionProps.TryGetValue(sectionName!, out var props))
                {
                    foreach (var prop in props)
                    {
                        var propAccess = $"{valueExpr}.{prop.Name}";
                        var effectiveSectionLevel = System.Math.Max(prop.SectionLevel, baseHeadingLevel);
                        EmitSectionProperty(sb, prop, propAccess, indent, indentLevel, effectiveSectionLevel, nestingDepth, fieldLayout, rootValueExpr, rootTypeName);
                    }
                }
            }
        }
    }

    private static void EmitScalarSectionGroup(
        StringBuilder sb,
        List<PropertyMetadata> props,
        PropertyMetadata firstProp,
        string sectionName,
        string valueExpr,
        string indent,
        int indentLevel,
        int baseHeadingLevel,
        int nestingDepth,
        FieldLayoutKind fieldLayout,
        string? rootValueExpr = null,
        string? rootTypeName = null)
    {
        var effectiveSectionLevel = System.Math.Max(firstProp.SectionLevel, baseHeadingLevel);

        // Emit ShowWhenProperty guard if configured (from first property's section config)
        var showWhenIndent = indent;
        var showWhenIndentLevel = indentLevel;
        if (firstProp.SectionShowWhenProperty != null && rootValueExpr != null)
        {
            sb.AppendLine($"{indent}if ({rootValueExpr}.{firstProp.SectionShowWhenProperty})");
            sb.AppendLine($"{indent}{{");
            showWhenIndent = indent + "    ";
            showWhenIndentLevel = indentLevel + 1;
        }

        // Emit per-section hook at top level only
        if (rootValueExpr != null && rootTypeName != null)
        {
            var safeName = new string(sectionName.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());
            var skipVar = $"__skipSection{safeName}";
            sb.AppendLine($"{showWhenIndent}var {skipVar} = false;");
            sb.AppendLine($"{showWhenIndent}OnBeforeSection{safeName}(writer, {rootValueExpr}, ref {skipVar});");
            sb.AppendLine($"{showWhenIndent}if (!{skipVar})");
            sb.AppendLine($"{showWhenIndent}{{");

            FieldEmitter.EmitScalarsWithLayout(sb, props, valueExpr, showWhenIndentLevel + 1, fieldLayout, nestingDepth,
                sectionHeading: sectionName, sectionLevel: effectiveSectionLevel, fieldOrder: firstProp.SectionFieldOrder);

            sb.AppendLine($"{showWhenIndent}}}");
        }
        else
        {
            FieldEmitter.EmitScalarsWithLayout(sb, props, valueExpr, showWhenIndentLevel, fieldLayout, nestingDepth,
                sectionHeading: sectionName, sectionLevel: effectiveSectionLevel, fieldOrder: firstProp.SectionFieldOrder);
        }

        if (firstProp.SectionShowWhenProperty != null && rootValueExpr != null)
        {
            sb.AppendLine($"{indent}}}");
        }
    }

    private static void EmitSectionProperty(
        StringBuilder sb,
        PropertyMetadata prop,
        string propAccess,
        string indent,
        int indentLevel,
        int effectiveSectionLevel,
        int nestingDepth,
        FieldLayoutKind fieldLayout,
        string? rootValueExpr = null,
        string? rootTypeName = null)
    {
        var sectionName = prop.SectionName ?? prop.DisplayName;

        // Emit ShowWhenProperty guard if configured
        var showWhenIndent = indent;
        var showWhenIndentLevel = indentLevel;
        if (prop.SectionShowWhenProperty != null && rootValueExpr != null)
        {
            sb.AppendLine($"{indent}if ({rootValueExpr}.{prop.SectionShowWhenProperty})");
            sb.AppendLine($"{indent}{{");
            showWhenIndent = indent + "    ";
            showWhenIndentLevel = indentLevel + 1;
        }

        // Emit per-section hook at top level only
        if (rootValueExpr != null && rootTypeName != null)
        {
            var safeName = new string(sectionName.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());
            var skipVar = $"__skip{prop.Name}";
            sb.AppendLine($"{showWhenIndent}var {skipVar} = false;");
            sb.AppendLine($"{showWhenIndent}OnBeforeSection{safeName}(writer, {rootValueExpr}, ref {skipVar});");
            sb.AppendLine($"{showWhenIndent}if (!{skipVar})");
            sb.AppendLine($"{showWhenIndent}{{");

            EmitSectionBody(sb, prop, propAccess, showWhenIndent + "    ", showWhenIndentLevel + 1, effectiveSectionLevel, nestingDepth, fieldLayout, sectionName, rootTypeName);

            sb.AppendLine($"{showWhenIndent}}}");
        }
        else
        {
            EmitSectionBody(sb, prop, propAccess, showWhenIndent, showWhenIndentLevel, effectiveSectionLevel, nestingDepth, fieldLayout, sectionName, rootTypeName);
        }

        if (prop.SectionShowWhenProperty != null && rootValueExpr != null)
        {
            sb.AppendLine($"{indent}}}");
        }
    }

    private static void EmitSectionBody(
        StringBuilder sb,
        PropertyMetadata prop,
        string propAccess,
        string indent,
        int indentLevel,
        int effectiveSectionLevel,
        int nestingDepth,
        FieldLayoutKind fieldLayout,
        string sectionName,
        string? rootTypeName = null)
    {
        var headlessArg = prop.SectionHeadless ? ", headless: true" : "";

        if (prop.Kind == PropertyKind.FieldCollection)
        {
            var writeMethod = prop.SectionHeadless ? "WriteFieldsInline" : "WriteFieldsTable";
            var fieldsExpression = prop.SectionFieldOrder == MarkoutFieldOrderKind.Alphabetical
                ? $"global::Markout.MarkoutFieldOrderer.Apply(global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan({propAccess}), global::Markout.MarkoutFieldOrder.Alphabetical)"
                : $"global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan({propAccess})";
            sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.Count > 0)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    writer.WriteSectionStart({effectiveSectionLevel}, \"{EmitHelpers.EscapeString(sectionName)}\"{headlessArg});");
            sb.AppendLine($"{indent}    writer.{writeMethod}({fieldsExpression});");
            sb.AppendLine($"{indent}    writer.WriteSectionEnd();");
            sb.AppendLine($"{indent}}}");
            EmitSectionEmptyFallback(sb, prop, propAccess, indent, effectiveSectionLevel, sectionName);
        }
        else if (prop.Kind == PropertyKind.ComplexArray && prop.ElementProperties != null)
        {
            sb.AppendLine($"{indent}if ({EmitHelpers.GetCollectionCountCheck(prop, propAccess)})");
            sb.AppendLine($"{indent}{{");

            // Emit dynamic ignore column conditions
            var dynamicIgnores = EmitIgnoreColumnWhenConditions(sb, prop, propAccess, indent + "    ", rootTypeName);

            if (prop.IsUnwrapped)
            {
                // Unwrapped: iterate items at the section level without a section heading
                CollectionEmitter.EmitSubsectionPerItemSerialization(sb, prop, propAccess, indentLevel + 1, effectiveSectionLevel - 1, nestingDepth);
            }
            else
            {
                sb.AppendLine($"{indent}    writer.WriteSectionStart({effectiveSectionLevel}, \"{EmitHelpers.EscapeString(sectionName)}\"{headlessArg});");

                if (prop.SectionGroupByProperty != null)
                {
                    // Grouped rendering: partition by property, subheading per group
                    CollectionEmitter.EmitGroupedSerialization(sb, prop, propAccess, indentLevel + 1, effectiveSectionLevel, dynamicIgnores);
                }
                else if (prop.MaxItems != null)
                {
                    var innerIndent = indent + "    ";
                    var (truncVar, _) = EmitHelpers.EmitMaxItemsTruncation(sb, prop, propAccess, innerIndent, nestingDepth);
                    if (prop.ElementHasNestedContent)
                    {
                        CollectionEmitter.EmitSubsectionPerItemSerialization(sb, prop, truncVar, indentLevel + 1, effectiveSectionLevel, nestingDepth);
                    }
                    else
                    {
                        CollectionEmitter.EmitTableSerialization(sb, prop, truncVar, indentLevel + 1, nestingDepth, dynamicIgnores);
                    }
                    EmitHelpers.EmitMaxItemsEllipsis(sb, prop, propAccess, innerIndent, nestingDepth);
                }
                else
                {
                    if (prop.ElementHasNestedContent)
                    {
                        CollectionEmitter.EmitSubsectionPerItemSerialization(sb, prop, propAccess, indentLevel + 1, effectiveSectionLevel, nestingDepth);
                    }
                    else
                    {
                        CollectionEmitter.EmitTableSerialization(sb, prop, propAccess, indentLevel + 1, nestingDepth, dynamicIgnores);
                    }
                }
                sb.AppendLine($"{indent}    writer.WriteSectionEnd();");
            }

            sb.AppendLine($"{indent}}}");
            if (!prop.IsUnwrapped)
                EmitSectionEmptyFallback(sb, prop, propAccess, indent, effectiveSectionLevel, sectionName);
        }
        else if (prop.Kind == PropertyKind.StringArray)
        {
            sb.AppendLine($"{indent}if ({EmitHelpers.GetCollectionCountCheck(prop, propAccess)})");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    writer.WriteSectionStart({effectiveSectionLevel}, \"{EmitHelpers.EscapeString(sectionName)}\"{headlessArg});");
            if (prop.MaxItems != null)
            {
                var innerIndent = indent + "    ";
                var (truncVar, _) = EmitHelpers.EmitMaxItemsTruncation(sb, prop, propAccess, innerIndent, nestingDepth);
                sb.AppendLine($"{innerIndent}writer.WriteArray({truncVar});");
                EmitHelpers.EmitMaxItemsEllipsis(sb, prop, propAccess, innerIndent, nestingDepth);
            }
            else
            {
                sb.AppendLine($"{indent}    writer.WriteArray(global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan({propAccess}));");
            }
            sb.AppendLine($"{indent}    writer.WriteSectionEnd();");
            sb.AppendLine($"{indent}}}");
            EmitSectionEmptyFallback(sb, prop, propAccess, indent, effectiveSectionLevel, sectionName);
        }
        else if (prop.Kind == PropertyKind.Tree)
        {
            sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.Count > 0)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    writer.WriteSectionStart({effectiveSectionLevel}, \"{EmitHelpers.EscapeString(sectionName)}\"{headlessArg});");
            if (prop.MaxItems != null)
            {
                var innerIndent = indent + "    ";
                var (truncVar, _) = EmitHelpers.EmitMaxItemsTruncation(sb, prop, propAccess, innerIndent, nestingDepth);
                sb.AppendLine($"{innerIndent}writer.WriteTree({truncVar});");
                EmitHelpers.EmitMaxItemsEllipsis(sb, prop, propAccess, innerIndent, nestingDepth);
            }
            else
            {
                sb.AppendLine($"{indent}    writer.WriteTree(global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan({propAccess}));");
            }
            sb.AppendLine($"{indent}    writer.WriteSectionEnd();");
            sb.AppendLine($"{indent}}}");
            EmitSectionEmptyFallback(sb, prop, propAccess, indent, effectiveSectionLevel, sectionName);
        }
        else if (prop.Kind == PropertyKind.Metric)
        {
            if (prop.IsScalarShape)
            {
                var (guard, value) = ScalarShapeAccess(prop, propAccess);
                sb.AppendLine($"{indent}if ({guard})");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    writer.WriteSectionStart({effectiveSectionLevel}, \"{EmitHelpers.EscapeString(sectionName)}\"{headlessArg});");
                sb.AppendLine($"{indent}    writer.WriteMetrics(new[] {{ {value} }});");
                sb.AppendLine($"{indent}    writer.WriteSectionEnd();");
                sb.AppendLine($"{indent}}}");
            }
            else
            {
                sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.Count > 0)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    writer.WriteSectionStart({effectiveSectionLevel}, \"{EmitHelpers.EscapeString(sectionName)}\"{headlessArg});");
                sb.AppendLine($"{indent}    writer.WriteMetrics({propAccess});");
                sb.AppendLine($"{indent}    writer.WriteSectionEnd();");
                sb.AppendLine($"{indent}}}");
            }
            EmitSectionEmptyFallback(sb, prop, propAccess, indent, effectiveSectionLevel, sectionName);
        }
        else if (prop.Kind == PropertyKind.Description)
        {
            sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.Count > 0)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    writer.WriteSectionStart({effectiveSectionLevel}, \"{EmitHelpers.EscapeString(sectionName)}\"{headlessArg});");
            sb.AppendLine($"{indent}    writer.WriteDescriptions({propAccess});");
            sb.AppendLine($"{indent}    writer.WriteSectionEnd();");
            sb.AppendLine($"{indent}}}");
            EmitSectionEmptyFallback(sb, prop, propAccess, indent, effectiveSectionLevel, sectionName);
        }
        else if (prop.Kind == PropertyKind.Breakdown)
        {
            if (prop.IsScalarShape)
            {
                var (guard, value) = ScalarShapeAccess(prop, propAccess);
                sb.AppendLine($"{indent}if ({guard})");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    writer.WriteSectionStart({effectiveSectionLevel}, \"{EmitHelpers.EscapeString(sectionName)}\"{headlessArg});");
                sb.AppendLine($"{indent}    writer.WriteBreakdown(new[] {{ {value} }});");
                sb.AppendLine($"{indent}    writer.WriteSectionEnd();");
                sb.AppendLine($"{indent}}}");
            }
            else
            {
                sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.Count > 0)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    writer.WriteSectionStart({effectiveSectionLevel}, \"{EmitHelpers.EscapeString(sectionName)}\"{headlessArg});");
                sb.AppendLine($"{indent}    writer.WriteBreakdown({propAccess});");
                sb.AppendLine($"{indent}    writer.WriteSectionEnd();");
                sb.AppendLine($"{indent}}}");
            }
            EmitSectionEmptyFallback(sb, prop, propAccess, indent, effectiveSectionLevel, sectionName);
        }
        else if (prop.Kind == PropertyKind.MetricChange)
        {
            var sectionArg = prop.SectionIncludeInStructuredRows ? $", \"{EmitHelpers.EscapeString(sectionName)}\"" : "";
            sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.{(prop.IsArray ? "Length" : "Count")} > 0)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    writer.WriteSectionStart({effectiveSectionLevel}, \"{EmitHelpers.EscapeString(sectionName)}\"{headlessArg});");
            sb.AppendLine($"{indent}    writer.WriteMetricChangeTable({propAccess}{sectionArg});");
            sb.AppendLine($"{indent}    writer.WriteSectionEnd();");
            sb.AppendLine($"{indent}}}");
            EmitSectionEmptyFallback(sb, prop, propAccess, indent, effectiveSectionLevel, sectionName);
        }
        else if (prop.Kind == PropertyKind.MultiSource)
        {
            var labelHeader = EmitHelpers.EscapeString(prop.MultiSourceLabelHeader ?? "Field");
            var sectionArg = prop.SectionIncludeInStructuredRows ? $", \"{EmitHelpers.EscapeString(sectionName)}\"" : "";
            sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.{(prop.IsArray ? "Length" : "Count")} > 0)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    writer.WriteSectionStart({effectiveSectionLevel}, \"{EmitHelpers.EscapeString(sectionName)}\"{headlessArg});");
            sb.AppendLine($"{indent}    writer.WriteMultiSourceTable(\"{labelHeader}\", {propAccess}{sectionArg});");
            sb.AppendLine($"{indent}    writer.WriteSectionEnd();");
            sb.AppendLine($"{indent}}}");
            EmitSectionEmptyFallback(sb, prop, propAccess, indent, effectiveSectionLevel, sectionName);
        }
        else if (prop.Kind == PropertyKind.CodeSection)
        {
            sb.AppendLine($"{indent}if ({propAccess}.Content != null)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    writer.WriteSectionStart({effectiveSectionLevel}, \"{EmitHelpers.EscapeString(sectionName)}\"{headlessArg});");
            sb.AppendLine($"{indent}    writer.WriteCodeStart({propAccess}.Language);");
            sb.AppendLine($"{indent}    writer.WriteParagraph({propAccess}.Content);");
            sb.AppendLine($"{indent}    writer.WriteCodeEnd();");
            sb.AppendLine($"{indent}    writer.WriteSectionEnd();");
            sb.AppendLine($"{indent}}}");
        }
        else if (prop.Kind == PropertyKind.NestedObject && prop.ElementProperties != null)
        {
            sb.AppendLine($"{indent}if ({propAccess} != null)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    writer.WriteSectionStart({effectiveSectionLevel}, \"{EmitHelpers.EscapeString(sectionName)}\"{headlessArg});");
            EmitPropertySerializations(sb, prop.ElementProperties, propAccess, indentLevel + 1, effectiveSectionLevel + 1, nestingDepth + 1, autoFields: prop.ElementAutoFields, fieldLayout: prop.ElementFieldLayout);
            sb.AppendLine($"{indent}    writer.WriteSectionEnd();");
            sb.AppendLine($"{indent}}}");
        }
        else if (prop.Kind == PropertyKind.Formattable)
        {
            sb.AppendLine($"{indent}if ({propAccess} != null)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    writer.WriteSectionStart({effectiveSectionLevel}, \"{EmitHelpers.EscapeString(sectionName)}\"{headlessArg});");
            sb.AppendLine($"{indent}    ((global::Markout.IMarkoutFormattable){propAccess}).WriteTo(writer);");
            sb.AppendLine($"{indent}    writer.WriteSectionEnd();");
            sb.AppendLine($"{indent}}}");
        }
        else
        {
            // For other types, just write the heading unconditionally
            sb.AppendLine($"{indent}writer.WriteSectionStart({effectiveSectionLevel}, \"{EmitHelpers.EscapeString(sectionName)}\"{headlessArg});");
            sb.AppendLine($"{indent}writer.WriteSectionEnd();");
        }
    }

    /// <summary>
    /// Emits condition variables for [MarkoutIgnoreColumnWhen] attributes and returns the list for CollectionEmitter.
    /// </summary>
    private static List<(string ConditionVar, string ColumnName)>? EmitIgnoreColumnWhenConditions(
        StringBuilder sb,
        PropertyMetadata prop,
        string propAccess,
        string indent,
        string? rootTypeName)
    {
        if (prop.SectionIgnoreColumnWhen == null || prop.SectionIgnoreColumnWhen.Count == 0 || rootTypeName == null)
            return null;

        var result = new List<(string, string)>();
        var usedVariableNames = new HashSet<string>();
        foreach (var (methodName, columnName) in prop.SectionIgnoreColumnWhen)
        {
            var condVar = CreateUniqueIgnoreConditionVariable(columnName, usedVariableNames);
            sb.AppendLine($"{indent}var {condVar} = {rootTypeName}.{methodName}({propAccess});");
            result.Add((condVar, columnName));
        }
        return result;
    }

    private static string CreateUniqueIgnoreConditionVariable(string columnName, HashSet<string> usedVariableNames)
    {
        var suffix = NormalizeSectionName(columnName);
        if (string.IsNullOrEmpty(suffix))
            suffix = "Column";

        var baseName = $"__ignore{suffix}";
        var name = baseName;
        var index = 2;
        while (!usedVariableNames.Add(name))
            name = baseName + index++;

        return name;
    }

    // Builds the (guard, value) pair for a scalar Metric/Breakdown property so it renders as its
    // bar shape via the single-item list overload. Nullable value types guard on HasValue and read
    // .Value; the shape guard skips a default/empty struct (avoids CS8073 value-type null checks).
    private static (string Guard, string Value) ScalarShapeAccess(PropertyMetadata prop, string propAccess)
    {
        var value = prop.IsNullableValueType ? $"{propAccess}.Value" : propAccess;
        var shapeGuard = prop.Kind == PropertyKind.Breakdown
            ? $"{value}.Slices is not null && {value}.Slices.Length > 0"
            : $"{value}.Label is not null";
        var guard = prop.IsNullableValueType ? $"{propAccess}.HasValue && {shapeGuard}" : shapeGuard;
        return (guard, value);
    }

    private static void EmitSectionEmptyFallback(
        StringBuilder sb,
        PropertyMetadata prop,
        string propAccess,
        string indent,
        int effectiveSectionLevel,
        string sectionName)
    {
        if (prop.SectionEmptyText == null)
            return;

        var headlessArg = prop.SectionHeadless ? ", headless: true" : "";
        sb.AppendLine($"{indent}else if ({propAccess} != null)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    writer.WriteSectionStart({effectiveSectionLevel}, \"{EmitHelpers.EscapeString(sectionName)}\"{headlessArg});");
        sb.AppendLine($"{indent}    writer.WriteParagraph(\"{EmitHelpers.EscapeString(prop.SectionEmptyText)}\");");
        sb.AppendLine($"{indent}    writer.WriteSectionEnd();");
        sb.AppendLine($"{indent}}}");
    }

    private static void EmitNonSectionProperty(
        StringBuilder sb,
        PropertyMetadata prop,
        string propAccess,
        string indent,
        int indentLevel,
        int baseHeadingLevel,
        int nestingDepth,
        FieldLayoutKind fieldLayout)
    {
        switch (prop.Kind)
        {
            case PropertyKind.StringArray:
                sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.Count > 0)");
                sb.AppendLine($"{indent}    writer.WriteArray(\"{EmitHelpers.EscapeString(prop.DisplayName)}\", global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan({propAccess}));");
                break;

            case PropertyKind.FieldCollection:
                sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.Count > 0)");
                sb.AppendLine($"{indent}    writer.WriteFieldsInline(global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan({propAccess}));");
                break;

            case PropertyKind.Tree:
                sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.Count > 0)");
                sb.AppendLine($"{indent}    writer.WriteTree(global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan({propAccess}));");
                break;

            case PropertyKind.Metric:
                if (prop.IsScalarShape)
                {
                    var (mGuard, mValue) = ScalarShapeAccess(prop, propAccess);
                    sb.AppendLine($"{indent}if ({mGuard})");
                    sb.AppendLine($"{indent}    writer.WriteMetrics(new[] {{ {mValue} }});");
                }
                else
                {
                    sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.Count > 0)");
                    sb.AppendLine($"{indent}    writer.WriteMetrics({propAccess});");
                }
                break;

            case PropertyKind.Description:
                sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.Count > 0)");
                sb.AppendLine($"{indent}    writer.WriteDescriptions({propAccess});");
                break;

            case PropertyKind.CodeSection:
                sb.AppendLine($"{indent}if ({propAccess}.Content != null)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    writer.WriteCodeStart({propAccess}.Language);");
                sb.AppendLine($"{indent}    writer.WriteParagraph({propAccess}.Content);");
                sb.AppendLine($"{indent}    writer.WriteCodeEnd();");
                sb.AppendLine($"{indent}}}");
                break;

            case PropertyKind.Callout:
                sb.AppendLine($"{indent}if ({propAccess}.Message != null)");
                sb.AppendLine($"{indent}    writer.WriteCallout({propAccess}.Severity, {propAccess}.Message);");
                break;

            case PropertyKind.Breakdown:
                if (prop.IsScalarShape)
                {
                    var (bGuard, bValue) = ScalarShapeAccess(prop, propAccess);
                    sb.AppendLine($"{indent}if ({bGuard})");
                    sb.AppendLine($"{indent}    writer.WriteBreakdown(new[] {{ {bValue} }});");
                }
                else
                {
                    sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.Count > 0)");
                    sb.AppendLine($"{indent}    writer.WriteBreakdown({propAccess});");
                }
                break;

            case PropertyKind.MetricChange:
                sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.{(prop.IsArray ? "Length" : "Count")} > 0)");
                sb.AppendLine($"{indent}    writer.WriteMetricChangeTable({propAccess});");
                break;

            case PropertyKind.MultiSource:
                sb.AppendLine($"{indent}if ({propAccess} != null && {propAccess}.{(prop.IsArray ? "Length" : "Count")} > 0)");
                sb.AppendLine($"{indent}    writer.WriteMultiSourceTable(\"{EmitHelpers.EscapeString(prop.MultiSourceLabelHeader ?? "Field")}\", {propAccess});");
                break;

            case PropertyKind.ComplexArray:
                if (prop.ElementProperties != null && prop.ElementProperties.Count > 0)
                {
                    sb.AppendLine($"{indent}if ({EmitHelpers.GetCollectionCountCheck(prop, propAccess)})");
                    sb.AppendLine($"{indent}{{");
                    if (prop.IsUnwrapped)
                    {
                        // Unwrapped: iterate items at current heading level without a parent heading
                        CollectionEmitter.EmitSubsectionPerItemSerialization(sb, prop, propAccess, indentLevel + 1, baseHeadingLevel - 1, nestingDepth);
                    }
                    else
                    {
                        sb.AppendLine($"{indent}    writer.WriteHeading({baseHeadingLevel}, \"{EmitHelpers.EscapeString(prop.DisplayName)}\");");
                        if (prop.ElementHasNestedContent)
                        {
                            CollectionEmitter.EmitSubsectionPerItemSerialization(sb, prop, propAccess, indentLevel + 1, baseHeadingLevel, nestingDepth);
                        }
                        else
                        {
                            CollectionEmitter.EmitTableSerialization(sb, prop, propAccess, indentLevel + 1, nestingDepth);
                        }
                    }
                    sb.AppendLine($"{indent}}}");
                }
                break;

            case PropertyKind.NestedObject:
                if (prop.ElementProperties != null && prop.ElementProperties.Count > 0)
                {
                    sb.AppendLine($"{indent}if ({propAccess} != null)");
                    sb.AppendLine($"{indent}{{");
                    sb.AppendLine($"{indent}    writer.WriteHeading({baseHeadingLevel}, \"{EmitHelpers.EscapeString(prop.DisplayName)}\");");
                    EmitPropertySerializations(sb, prop.ElementProperties, propAccess, indentLevel + 1, baseHeadingLevel + 1, nestingDepth + 1, true, 0, fieldLayout);
                    sb.AppendLine($"{indent}}}");
                }
                break;

            case PropertyKind.Formattable:
                sb.AppendLine($"{indent}if ({propAccess} != null)");
                sb.AppendLine($"{indent}    ((global::Markout.IMarkoutFormattable){propAccess}).WriteTo(writer);");
                break;
        }
    }

    private static void EmitSchemaProperty(StringBuilder sb, TypeMetadata type)
    {
        sb.AppendLine($"    private static global::Markout.MarkoutSchemaInfo? _{type.TypeName}Schema;");
        sb.AppendLine($"    public static global::Markout.MarkoutSchemaInfo {type.TypeName}Schema => _{type.TypeName}Schema ??= new()");
        sb.AppendLine("    {");
        sb.AppendLine($"        TypeName = \"{type.TypeName}\",");
        sb.AppendLine($"        AsDocument = new global::Markout.MarkoutPropertySchema[]");
        sb.AppendLine("        {");
        EmitSchemaProperties(sb, type.Properties, false, 3);
        sb.AppendLine("        },");
        sb.AppendLine($"        AsTableItem = new global::Markout.MarkoutPropertySchema[]");
        sb.AppendLine("        {");
        EmitSchemaProperties(sb, type.Properties, true, 3);
        sb.AppendLine("        }");
        sb.AppendLine("    };");
        sb.AppendLine();
    }

    private static void EmitSchemaProperties(StringBuilder sb, IReadOnlyList<PropertyMetadata> properties, bool inTableContext, int indentLevel)
    {
        var indent = new string(' ', indentLevel * 4);

        foreach (var prop in properties)
        {
            var rendering = GetRenderingDescription(prop, inTableContext);
            
            sb.AppendLine($"{indent}new()");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    Name = \"{prop.Name}\",");
            sb.AppendLine($"{indent}    DisplayName = \"{EmitHelpers.EscapeString(prop.DisplayName)}\",");
            sb.AppendLine($"{indent}    TypeName = \"{EmitHelpers.EscapeString(GetSimpleTypeName(prop.TypeName))}\",");
            sb.AppendLine($"{indent}    Rendering = \"{EmitHelpers.EscapeString(rendering)}\",");
            
            // Only show children for non-ignored properties in document context
            if (prop.ElementProperties != null && prop.ElementProperties.Count > 0 && !inTableContext && !prop.IsIgnored)
            {
                sb.AppendLine($"{indent}    Children = new global::Markout.MarkoutPropertySchema[]");
                sb.AppendLine($"{indent}    {{");
                // For sections, show child properties as they would render
                var childInTable = prop.Kind == PropertyKind.ComplexArray && !prop.ElementHasNestedContent;
                EmitSchemaProperties(sb, prop.ElementProperties, childInTable, indentLevel + 2);
                sb.AppendLine($"{indent}    }}");
            }
            else
            {
                sb.AppendLine($"{indent}    Children = global::System.Array.Empty<global::Markout.MarkoutPropertySchema>()");
            }
            
            sb.AppendLine($"{indent}}},");
        }
    }

    private static void EmitSectionConstants(StringBuilder sb, TypeMetadata type)
    {
        var sectionProps = type.Properties
            .Where(p => p.IsSection && !p.IsIgnored)
            .ToList();

        if (sectionProps.Count == 0)
            return;

        sb.AppendLine($"    public static class {type.TypeName}Sections");
        sb.AppendLine("    {");

        var usedNames = new HashSet<string>();
        foreach (var prop in sectionProps)
        {
            var sectionName = prop.SectionName ?? prop.DisplayName;
            var constName = NormalizeSectionName(sectionName);

            // Ensure uniqueness by appending a suffix if needed
            var uniqueName = constName;
            var suffix = 2;
            while (!usedNames.Add(uniqueName))
            {
                uniqueName = constName + suffix;
                suffix++;
            }

            sb.AppendLine($"        public const string {uniqueName} = \"{EmitHelpers.EscapeString(sectionName)}\";");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string GetTypeInfoClassName(TypeMetadata type)
    {
        if (string.IsNullOrEmpty(type.Namespace))
            return $"global::{type.TypeName}MarkoutTypeInfo";
        return $"global::{type.Namespace}.{type.TypeName}MarkoutTypeInfo";
    }

    private static string NormalizeSectionName(string name)
    {
        // Replace non-alphanumeric characters with spaces, then PascalCase join
        var cleaned = new StringBuilder(name.Length);
        foreach (var ch in name)
        {
            cleaned.Append(char.IsLetterOrDigit(ch) ? ch : ' ');
        }

        var parts = cleaned.ToString().Split(new[] { ' ' }, System.StringSplitOptions.RemoveEmptyEntries);
        var result = new StringBuilder();
        foreach (var part in parts)
        {
            result.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
                result.Append(part.Substring(1));
        }
        return result.ToString();
    }

    private static string GetRenderingDescription(PropertyMetadata prop, bool inTableContext)
    {
        if (inTableContext)
        {
            if (prop.IsIgnored)
                return "Ignored";
            
            if (prop.IsIgnoredInTable)
                return "Ignored";

            // The child flag is a nesting marker (rendered as a glyph), never a table column.
            if (prop.IsChildFlag)
                return "Ignored";
            
            // In table context, only scalars (and joined arrays) work
            if (EmitHelpers.IsScalarKind(prop.Kind) || EmitHelpers.IsJoinedArray(prop))
                return "Column" + (prop.Name != prop.DisplayName ? $" \"{prop.DisplayName}\"" : "");
            
            // Unsupported patterns are skipped
            if (prop.IsUnsupportedInTable)
                return "Skipped (unsupported)";
            
            return "Column";
        }

        if (prop.IsIgnored)
            return "Ignored";

        // Document context - [MarkoutIgnoreInTable] has no effect here
        if (prop.IsSection)
        {
            var sectionName = prop.SectionName ?? prop.DisplayName;
            if (EmitHelpers.IsScalarKind(prop.Kind))
                return $"H{prop.SectionLevel} Section \"{sectionName}\" (field)";
            if (prop.Kind == PropertyKind.FieldCollection)
                return $"H{prop.SectionLevel} Section \"{sectionName}\" (field table)";
            if (prop.Kind == PropertyKind.ComplexArray)
            {
                if (prop.ElementHasNestedContent)
                    return $"H{prop.SectionLevel} Section \"{sectionName}\" (subsections)";
                return $"H{prop.SectionLevel} Section \"{sectionName}\" (table)";
            }
            if (prop.Kind == PropertyKind.NestedObject)
                return $"H{prop.SectionLevel} Section \"{sectionName}\" (fields)";
            if (prop.Kind == PropertyKind.Tree)
                return $"H{prop.SectionLevel} Section \"{sectionName}\" (tree)";
            if (prop.Kind == PropertyKind.Metric)
                return $"H{prop.SectionLevel} Section \"{sectionName}\" (bar chart)";
            if (prop.Kind == PropertyKind.Description)
                return $"H{prop.SectionLevel} Section \"{sectionName}\" (labeled list)";
            if (prop.Kind == PropertyKind.CodeSection)
                return $"H{prop.SectionLevel} Section \"{sectionName}\" (code block)";
            if (prop.Kind == PropertyKind.Breakdown)
                return $"H{prop.SectionLevel} Section \"{sectionName}\" (distribution)";
            if (prop.Kind == PropertyKind.MetricChange)
                return $"H{prop.SectionLevel} Section \"{sectionName}\" (gated metrics)";
            if (prop.Kind == PropertyKind.MultiSource)
                return $"H{prop.SectionLevel} Section \"{sectionName}\" (multi-source)";
            return $"H{prop.SectionLevel} Section \"{sectionName}\"";
        }

        return prop.Kind switch
        {
            PropertyKind.String => "Field",
            PropertyKind.Boolean => "Field (yes/no)",
            PropertyKind.Int32 or PropertyKind.Int64 => "Field",
            PropertyKind.Double or PropertyKind.Decimal => "Field",
            PropertyKind.DateTime or PropertyKind.DateTimeOffset => "Field (ISO 8601)",
            PropertyKind.Enum => "Field (enum)",
            PropertyKind.StringArray => prop.JoinSeparator != null ? "Field (joined)" : "Bullet list",
            PropertyKind.ComplexArray => prop.JoinSeparator != null
                ? "Field (joined)"
                : prop.ElementHasNestedContent ? "Subsections" : "Table",
            PropertyKind.FieldCollection => "Field list",
            PropertyKind.NestedObject => "Fields",
            PropertyKind.Formattable => "Custom (IMarkoutFormattable)",
            PropertyKind.Tree => "Tree",
            PropertyKind.Metric => "Metric",
            PropertyKind.Description => "Description",
            PropertyKind.CodeSection => "Code",
            PropertyKind.Callout => "Callout",
            PropertyKind.Breakdown => "Breakdown",
            PropertyKind.MetricChange => "MetricChange",
            PropertyKind.MultiSource => "MultiSource",
            _ => "Field"
        };
    }

    private static string GetSimpleTypeName(string fullTypeName)
    {
        // Simplify common type names
        return fullTypeName
            .Replace("System.Collections.Generic.List<", "List<")
            .Replace("System.String", "string")
            .Replace("System.Int32", "int")
            .Replace("System.Int64", "long")
            .Replace("System.Boolean", "bool")
            .Replace("System.Decimal", "decimal")
            .Replace("System.Double", "double");
    }
}
